### ISSUE TITLE
[Bug] Cannot find src - 8.2.1 breaking changes

### ISSUE THREAD

**Issue by tyleralbee** [egoist/tsup#1161] opened 2024-07-21 00:57 UTC
My project builds just fine on version `8.2.0` but is unable to build on [`8.2.1`](https://github.com/egoist/tsup/releases/tag/v8.2.1).

When running `pnpm i` on `8.2.1`:

```sh
# after running pnpm install
packages/redacted
│└─┬ tsup 8.2.1
│  └─┬ fdir 6.1.1
│    └── ✕ unmet peer picomatch@3.x: found 4.0.2 in tsup 
```

When running `tsup`:
```sh
# after running tsup
> tsup

Cannot find src
```

Installing peers did not fix the issue for me; pinning my version to `8.2.0` in my `package.json` fixed the issue.

```jsonc
// package.json
"tsup": "8.2.0"
```

My tsconfig:
```jsonc
{
    "compilerOptions": {
        "rootDir": ".",
        "outDir": "dist"
    },
    "include": ["**/*.ts", ".eslintrc.cjs"]
}
```

My `tsup.config.ts`:
```ts
import { defineConfig } from "tsup";

const tsupConfig = defineConfig({
    entry: ["src"],
    format: ["esm"]
})

export default tsupConfig;
```

The relevant parts of my package.json:
```json
{
    "name": "@monorepo/redacted",
    "type": "module",
    "exports": {
        "./redacted": {
            "types": "./src/redacted.ts",
            "import": "./dist/redacted.js"
        }
    },
    "scripts": {
        "build": "tsup"
    },
    "devDependencies": {
        "tsup": "8.2.1",
        "typescript": "5.5.3"
    },
    "packageManager": "pnpm@9.5.0",
    "engines": {
        "node": ">=20"
    }
}
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/egoist) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/egoist/tsup/issues/1161">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/egoist/tsup/issues/1161/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/egoist/tsup/issues/1161/pledge.svg">
</picture>
</a>

**Comment by SuperchupuDev** [comment] 2024-07-21 10:01
caused by #1158's globbing library switch, will try to fix

**Comment by SuperchupuDev** [comment] 2024-07-21 15:14
by the way, (until the fix gets released) replacing `"src"` with `"src/**"` should work as a workaround

**Comment by egoist** [comment] 2024-07-22 08:57
Fixed in https://github.com/egoist/tsup/releases/tag/v8.2.2

**Closed by egoist** 2024-07-22 08:57 UTC
